#!/usr/bin/env python3
"""
StageMon .arb <-> CSV bridge for non-programmer translators.
No external dependencies required — uses only Python standard library.

Workflow:
    1. export a CSV for the target language:
           python tools/l10n_sheet.py export fr
       -> writes lib/l10n/translations_fr.csv (key, en, es, notes, fr)
       The "es" column is a read-only reference copied from app_es.arb
       (omitted when the target language is es itself). If app_fr.arb
       already exists, its strings pre-fill the last column so
       collaborators only need to fill in the blanks.

    2. Import that CSV into Google Sheets (File > Import), share it with
       the translator, and have them edit only the last column.

    3. Download the sheet as CSV and import it back:
           python tools/l10n_sheet.py import es lib/l10n/translations_es.csv
       -> writes/overwrites lib/l10n/app_es.arb, validating that every
       {placeholder} from the English source is still present in each
       translated string.

    4. Run `flutter gen-l10n` (or just `flutter run`) to regenerate the
       Dart localization classes.

Only lib/l10n/app_en.arb (the template) is ever read as the source of
truth for keys and placeholders — .dart files under lib/l10n/ are
generated by flutter gen-l10n and must never be hand-edited or fed
back into this script.
"""
import argparse
import csv
import json
import re
import sys
from pathlib import Path

L10N_DIR = Path(__file__).resolve().parent.parent / "lib" / "l10n"
TEMPLATE_FILE = L10N_DIR / "app_en.arb"

PLACEHOLDER_RE = re.compile(r"\{(\w+)")


def load_arb(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def arb_keys(arb: dict):
    return [k for k in arb if not k.startswith("@")]


def placeholders_in(text: str) -> set:
    return set(PLACEHOLDER_RE.findall(text))


def cmd_export(args):
    template = load_arb(TEMPLATE_FILE)
    existing_path = L10N_DIR / f"app_{args.locale}.arb"
    existing = load_arb(existing_path) if existing_path.exists() else {}

    include_es_reference = args.locale != "es"
    spanish_path = L10N_DIR / "app_es.arb"
    spanish = load_arb(spanish_path) if include_es_reference and spanish_path.exists() else {}

    header = ["key", "en"]
    if spanish:
        header.append("es")
    header += ["notes", args.locale]

    out_path = Path(args.out) if args.out else L10N_DIR / f"translations_{args.locale}.csv"
    with out_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for key in arb_keys(template):
            en_text = template[key]
            placeholders = placeholders_in(en_text)
            notes = ""
            if placeholders:
                notes = "Keep exactly: " + ", ".join(sorted("{%s}" % p for p in placeholders))
            row = [key, en_text]
            if spanish:
                row.append(spanish.get(key, ""))
            row += [notes, existing.get(key, "")]
            writer.writerow(row)

    print(f"Wrote {out_path} ({len(arb_keys(template))} strings).")
    if existing:
        print(f"Pre-filled from existing {existing_path.name}.")


def cmd_import(args):
    template = load_arb(TEMPLATE_FILE)
    rows = {}
    with open(args.csv_file, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None or args.locale not in reader.fieldnames:
            sys.exit(
                f"error: CSV has no '{args.locale}' column. "
                f"Found columns: {reader.fieldnames}"
            )
        for row in reader:
            rows[row["key"]] = row

    errors = []
    warnings = []
    result = {"@@locale": args.locale}

    for key in arb_keys(template):
        row = rows.get(key)
        en_text = template[key]
        if row is None:
            errors.append(f"  - '{key}': missing from CSV")
            continue

        translated = row.get(args.locale, "")
        if translated is None or translated.strip() == "":
            warnings.append(f"  - '{key}': empty, falling back to English")
            translated = en_text

        expected = placeholders_in(en_text)
        actual = placeholders_in(translated)
        missing = expected - actual
        if missing:
            errors.append(
                f"  - '{key}': missing placeholder(s) "
                + ", ".join(sorted("{%s}" % p for p in missing))
                + f" -> {translated!r}"
            )
            continue

        result[key] = translated

    if warnings and not args.quiet:
        print(f"{len(warnings)} untranslated string(s):")
        print("\n".join(warnings))

    if errors:
        print(f"\n{len(errors)} error(s), nothing written:", file=sys.stderr)
        print("\n".join(errors), file=sys.stderr)
        sys.exit(1)

    out_path = L10N_DIR / f"app_{args.locale}.arb"
    with out_path.open("w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"\nWrote {out_path} ({len(arb_keys(template))} strings).")
    print("Run `flutter gen-l10n` next.")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p_export = sub.add_parser("export", help="Write a CSV for translators from app_en.arb")
    p_export.add_argument("locale", help="Language code, e.g. fr, pt, de")
    p_export.add_argument("--out", help="Output CSV path (default: lib/l10n/translations_<locale>.csv)")
    p_export.set_defaults(func=cmd_export)

    p_import = sub.add_parser("import", help="Write app_<locale>.arb from a translated CSV")
    p_import.add_argument("locale", help="Language code, e.g. fr, pt, de")
    p_import.add_argument("csv_file", help="CSV downloaded from the translators' spreadsheet")
    p_import.add_argument("--quiet", action="store_true", help="Don't list untranslated strings")
    p_import.set_defaults(func=cmd_import)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
